### ISSUE TITLE
could not convert string to float: 'NA'

### ISSUE THREAD

**Issue by lxcfuji** [huBioinfo/CytoTalk#12]
Hi Dr. Hu,

I'm getting another error showing below.

Traceback (most recent call last):
  File "gen_PCSF.py", line 11, in <module>
    Cost = numpy.loadtxt("IntegratedNet_edgeCost.txt", dtype = 'float')
  File "/home/rstudio/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1148, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/rstudio/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 999, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/rstudio/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 999, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/rstudio/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 736, in floatconv
    return float(x)
ValueError: could not convert string to float: 'NA'
[1] "2021-08-30 13:14:19 UTC"
[1] "(6/7) Generating the final signaling network between the two cell types...(around 25 min)"
Error in { : task 1 failed - "missing value where TRUE/FALSE needed"
Calls: genSignalingNetwork ... genSummaryPCSF -> runAnalysisFile -> %dopar% -> <Anonymous>
Execution halted

there's no "IntegratedNet_edgeCost.txt" saved under output, but checked my "IntegratedNet_edgeCost_common.txt" and it's all NAs. but "MutualInfo_TypA_Para.txt" and "MutualInfo_TypB_Para.txt" are good. looks like something wrong when generating edge cost?
please advise.

thank you so much!

**Comment by lxcfuji** [comment]
closed because it's same as issue #11
